version: '3'
services:
  nginx:
    image: nginx:1.13-alpine
    volumes:
      - ./nginx/sre.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - 80:80
    links:
      - app
  app:
    build: ./app


  sidecar:
    hostname: nginx
    image: gonitro/sidecar:latest
    cap_add:
      - NET_ADMIN
    labels:
      SidecarDiscover: "true"
    environment:
      - SIDECAR_LOGGING_LEVEL=debug
      - SIDECAR_SEEDS=127.0.0.1
      - SIDECAR_CLUSTER_NAME=development
      - "SIDECAR_DISCOVERY=docker static"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 10000-10050:10000-10050
      - 1777:7777
